<?php

namespace ASFF\TournoisBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionsTournoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionsTournoisRepository extends EntityRepository
{
	public function findByUserAndTournois($user, $tournois)
	{
	  $qb = $this->createQueryBuilder('a');

	  $qb->where('a.user = :user')->setParameter('user', $user)
		 ->andWhere('a.tournois = :tournois')->setParameter('tournois', $tournois)
		 ->orderBy('a.id', 'DESC');

	  return $qb->getQuery()->getOneOrNullResult();
	}
}
