<?php

namespace ASFF\TournoisBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TournoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournoisRepository extends EntityRepository
{
	
}
