# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        ASFF\UserBundle\Entity\Users: plaintext

    role_hierarchy:
        ROLE_BUREAU:        [ROLE_JOUEUR]
        ROLE_WEBMASTER:     [ROLE_BUREAU]
        ROLE_ADMIN:         [ROLE_WEBMASTER, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            pattern:    ^/
            anonymous:  true
            provider:   main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login
            remember_me:
                secret:     %secret%
            
    access_control:
        - { path: ^/admin, ip: 127.0.0.1, requires_channel: https }
